### ISSUE TITLE
Progress Logik verkehrt

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#127]
Mein Verständnis:

1. Alle Scanner werden gestartet
2. Es wird gewartet, bis alle Scanner fertig oder fehlgeschlagen sind
3. Der Scan Status geht dann von 2 auf 3
4. Die Ergebnisse werden angezeigt 

Meine Beobachtung:
Bevor alle Scanner gestartet sind wird bereits der Fortschritt ermittelt. Das hat zur Folge daß z.B. 4 Scanner gestartet wurden, 4 bereits durch sind und der Scan als fertig betrachtet wird, obwohl noch ein fünfter Scan ansteht.

Indiz:

```
Jul 12 12:25:49 bla.staging2.siwecos.de php: coreapi.INFO: Get Progress from id: 69399 for http://www… []
Jul 12 12:25:49 bla.staging2.siwecos.de php: coreapi.INFO: Progress: 4 4 0 []
Jul 12 12:25:49 bla.staging2.siwecos.de php: coreapi.INFO: 100 []
Jul 12 12:25:49 bla.staging2.siwecos.de php: coreapi.INFO: Ready to update 69399 to status 3 []
Jul 12 12:25:49 bla.staging2.siwecos.de php: coreapi.INFO: Done updating   69399 to status 3 []
Jul 12 12:25:50 bla.staging2.siwecos.de php: coreapi.INFO: StatusCode for INI_S (69399): 200 []
Jul 12 12:25:50 bla.staging2.siwecos.de php: coreapi.INFO: Callback Routehttps://ca.staging2.siwecos.de/api/v1/callback/346632 []
Jul 12 12:25:50 bla.staging2.siwecos.de php: coreapi.INFO: WS_TLS has started []
Jul 12 12:25:50 bla.staging2.siwecos.de php: coreapi.INFO: Progress: 5 4 1 []
Jul 12 12:25:50 bla.staging2.siwecos.de php: coreapi.INFO: 100 []
Jul 12 12:25:52 bla.staging2.siwecos.de php: coreapi.INFO: Progress: 5 4 1 []
Jul 12 12:25:52 bla.staging2.siwecos.de php: coreapi.INFO: 100 []
Jul 12 12:25:55 bla.staging2.siwecos.de php: coreapi.INFO: Progress: 5 4 1 []
Jul 12 12:25:55 bla.staging2.siwecos.de php: coreapi.INFO: 100 []
Jul 12 12:25:58 bla.staging2.siwecos.de php: coreapi.INFO: Progress: 5 4 1 []
Jul 12 12:25:58 bla.staging2.siwecos.de php: coreapi.INFO: 100 []
Jul 12 12:26:01 bla.staging2.siwecos.de php: coreapi.INFO: Progress: 5 4 1 []
Jul 12 12:26:01 bla.staging2.siwecos.de php: coreapi.INFO: 100 []
Jul 12 12:26:02 bla.staging2.siwecos.de php: coreapi.INFO: Max Schedule: 0 []
Jul 12 12:26:04 bla.staging2.siwecos.de php: coreapi.INFO: Progress: 5 4 1 []
```

Weitere Beobachtung:
TLS für diese Domain schlägt fehl. Darum habe ich in getProgress fehlgeschlagene Scans mit ermittelt (die dritte Stelle in obigen "Progress:" Zeilen, 5 4 1 also) und entsprechend zurückgeliefert.

Es scheint aber als ob nun der Status nie wieder auf 3 geht, da er bereits vorher mal auf 3 gesetzt wurde?

Bitte genauer analysieren und beheben.

**Comment by Skeeve** [comment]
@Skeeve Testen ob das noch der Fall ist.
Logeinträge für @Lednerb erkl#ären.

**Comment by Skeeve** [comment]
Erklärung der Logeinträge:

```
            Log::info('Progress: '.$allResults.' '.$doneResults.' '.$errResults);
            Log::info(round((($doneResults + $errResults) / $allResults) * 100));
```

Also bedeutet
```
5 4 1
```
5 Ergebnisse werden erwartet
4 sind durch
1 ist Error

**Comment by Skeeve** [comment]
Anhand der Logs läßt sich das nun nicht mehr finden, da die "5" aus dem Environment geholt wird.

**Comment by Lednerb** [comment]
Okay, `getProgress` sollte nun immer das korrekte Ergebnis liefern:

https://github.com/SIWECOS/siwecos-core-api/blob/13d4ea7f40b7c25f2206aa457298f0a6a2a3f8c9/app/Scan.php#L34-L55

Es wird stets durch die Anzahl der konfigurierten Scanner geteilt.

Früher wurde einmal in der Datenbank `$this->results()->count()` verwendet, was das Problem verursachen konnte.

**Comment by Skeeve** [comment]
Sieht gut aus.
