### ISSUE TITLE
Datenbank cleanup

### ISSUE THREAD

**Issue by Weegy** [SIWECOS/siwecos-core-api#148]
- nicht validierte User nach einer Woche löschen
- Alte Ergebnisse -> Elastic Search
- Domains bleiben

**Comment by Skeeve** [comment]
Medium: Elastic-Search
Low: Cleanup

**Comment by Lednerb** [comment]
Abhängig von https://github.com/SIWECOS/siwecos-business-layer/issues/83

Wird in der BLA behandelt.

**Comment by Lednerb** [comment]
Datenbank hat neue Struktur, keine Migration nötig.
