### ISSUE TITLE
resultRaw (vielleicht auch andere) liefern die falschen Scanergebnisse

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#157]
```
            $latestScan = Scan::whereUrl($domain->domain)->whereStatus(3)->latest()->first();
```

Vermutlich in der Zeile hier (ScanController.php) werden nicht die freescan Ergebnisse weggefiltert. Somit zeigt ein Abfrage eines registrierten Nutzers die Scan Ergebnisse des letzten Freescans wenn der jünger ist.

Siehe dazu ein Beispiel auf https://github.com/SIWECOS/webapp/issues/7

**Comment by Skeeve** [comment]
Link zum Code: 
https://github.com/SIWECOS/siwecos-core-api/blob/9c1cc105e8eee85e3ea420a844bb97d89db4a9cf/app/Http/Controllers/ScanController.php#L212

**Comment by Lednerb** [comment]
Gefixt in #185 und fbece82
