### ISSUE TITLE
Gemeinsamer User-Agent String

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#158]
Momentan kommen einige Anfragen warum domains nicht registriert werden können.

Einige davon sind dem Umstand geschuldet, dass die Domains den (Standard?) User-Agent String von Guzzle(?) mit einem Error 404 beantworten.

Wir hatten ähnliche Probleme bereits mit Scannern.

Wir benötigen also einen (definierbaren) User-Agent String, der von allen Komponenten in jeder Situation auch verwendet wird.

**Comment by Lednerb** [comment]
@ic0ns Ich nehme an, der TLS-Scanner sendet keinen User-Agent bzw. dieser wird nicht benötigt?

Ansonsten bitte kurz hier schauen, für weitere Informationen:
https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/issues/55

**Comment by ic0ns** [comment]
Richtig, für die scans die wir in Siwecos machen brauchen wir keinen useragent

**Comment by Lednerb** [comment]
Implementiert. Der HSHS-Scaner übernimmt den userAgent nun auch.
