### ISSUE TITLE
core ist nicht für parallelbetrieb geeignet

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#163]
Wir haben mehrere Core Instanzen gleichzeitig laufen.

Wenn es darum geht einen recurrent scan zu starten, bekommen u.U. alle cores dieselbe Domain aus der Datenbank, weil es hier keine Art der Synchronisierung gibt.

Jeder Core fragt nach einer Domain und startet scans für diese. Dummerweise liegt zwischen dem Erhalt und dem Starten genügend Zeit, damit weitere cores dieselbe Domain erhalten können.

Hier muß DRINGEND was geändert werden.

Vielleicht auch zunächst mal nur einen core laufen lassen für recurrent scans und einen weiteren für User?

**Comment by Skeeve** [comment]
In dem Zusammenhang die Fragen:

- Warum brauchen wir mehrere Core Instanzen? Reicht nicht eine für User und eine für recurrent scans?
- Wozu dient redis?

**Comment by Lednerb** [comment]
Redis wird zur JobQueue genutzt.

@Weegy hat das Deployment umgestellt:
Momentan je 1 Instanz von Core und BLA in `production` und `staging` Umgebung.
