### ISSUE TITLE
Datenbank Backups

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#170]
Fragen:

1. Gibt es Datenbank Backups?
1. Wenn ja - wie können wir sie nutzen?
1. Wenn nein - wie können wir möglichst schnell regelmäßige Backups einrichten?

**Comment by Skeeve** [comment]
Dump schlägt leider fehl…

```
$ mysqldump --all-databases -u $DB_USERNAME -p -h $DB_HOST --result-file=siwecos.dump-2018-11-22 --set-gtid-purged=OFF --triggers --routines --events
Enter password:
mysqldump: Got error: 1227: Access denied; you need (at least one of) the SUPER privilege(s) for this operation when using LOCK TABLES
```

**Comment by Lednerb** [comment]
@Skeeve @Weegy Neuigkeiten hierzu? --> Prio:High

**Comment by Lednerb** [comment]
Seitens @Weegy 

>Natürlich gibt's Datenbank Backups
>7 Tage Retention
>Lassen sich über die Konsole einspielen
>Direkt über Google MySQL

Datenbanken werden bis spätestens Sonntag getrennt sein.
