### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#171]
Unsortierte Schlagworte:

- Infrastruktur
- Troubleshooting
- Housekeeping
- Monitoring
- Performance Analyse
- Credentials

**Comment by Lednerb** [comment]
Abhängig von https://github.com/SIWECOS/siwecos-business-layer/issues/83

Macht danach erst Sinn.

**Comment by Lednerb** [comment]
Für den Core-API Teil in der README.md verlinkt, andere Dokus an entsprechender Stelle werden folgen.
