### ISSUE TITLE
Domains mit / am Ende?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#173]
Seit dem 1.11. 10:03:43 spätestens scheint es möglich zu sein, Domains mit "/" am Ende einzutragen.

Bisher wurde dieser, m.W. immer abgetrennt.

Nun ist es möglich, eine Domain doppelt zu registrieren.

Einmal mit, einmal ohne "/" am Ende.

also

- http://botfrei.de/
- http://botfrei.de

**Comment by Skeeve** [comment]
Ich habe gerade etwas in der DB aufgeräumt.

Es bleiben aber 4 Fälle in denen Domains auf diese Art doppelt registriert wurden.

Um das künftig zu vermeiden, sollte der Bug möglichst schnell behoben werden.

Ich habe einen Verdacht, woran es liegt und werde gleich noch Informationen dazu anhängen.

**Comment by Skeeve** [comment]
http://www.hradek.de/joomla/ -> Sogar das läßt sich registrieren.

https://github.com/SIWECOS/siwecos-core-api/blob/1da17d7d9abeb32676e21b6804cf81420fa910f5/app/Domain.php#L161

Hier wird die übergebene URL zerlegt. Sie müßte nun neu zusammengabaut werden, unter Verwendung des "host" Eintrags. Stattdessen wird die $testDomain durchgängig verwendet.

**Comment by Lednerb** [comment]
Fix implementiert in cc39160, weitere Infos unter #180

**Comment by Skeeve** [comment]
Funktioniert in staging. Allerdings würde ich empfehlen, auf der Domain-Verifizierungsseite die Domain des Nutzer nochmal explizit aufzuführen.

1. Ist das für den Nutzer hilfreich
1. Kann er nur so feststellen, dass SIWECOS an seiner Eingabe "rumgespielt" hat.

Siehe dazu: https://github.com/SIWECOS/webapp/issues/14

**Comment by Skeeve** [comment]
Wir haben erneut 427(!) Einträge in domains die mehr als das Protokoll und den Hostadresse beinhalten.

**Comment by Lednerb** [comment]
Wird in der BLA nicht mehr vorkommen, siehe hier:

https://github.com/SIWECOS/siwecos-business-layer/blob/5d3d7d933499cb6ef0921c1285967d2b94ca9f76/tests/Feature/DomainRegistrationTest.php#L33-L53
