### ISSUE TITLE
Falsche Fehlermeldung wenn eine Domain versucht wird ein 2tes Mal einzutragen

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#174]
Der Versuch botfrei.de erneut einzufügen wird mit diesem Fehler beantwortet:

![image](https://user-images.githubusercontent.com/725404/48907956-4d42cb80-ee69-11e8-828a-00d30ff4726c.png)

Console zeigt HTTP response 409.

**Comment by Skeeve** [comment]
Ich habe @SniperSister mit hinzugefügt, weil ich nicht weiß, ob's an der webapp oder am core liegt.

**Comment by SniperSister** [comment]
Die entsprechenden Commits waren in der Live noch nicht drin, hab ich gerade nachgezogen. Bitte in ner halben Stunde nochmal testen

**Comment by SniperSister** [comment]
@Skeeve bitte nochmal verfizieren

**Comment by Skeeve** [comment]
Funktioniert. Allerdings würde ich empfehlen, auf der Domain-Verifizierungsseite die Domain des Nutzer nochmal explizit aufzuführen.

1. Ist das für den Nutzer hilfreich
1. Kann er nur so feststellen, dass SIWECOS an seiner Eingabe "rumgespielt" hat.

Siehe dazu: https://github.com/SIWECOS/webapp/issues/14

**Comment by SniperSister** [comment]
Ok, wir können aber feststellen, das der Teil hier funktioneirt, right? Ticket kann also geschlossen werdne?

**Comment by Skeeve** [comment]
Funktioniert!
