### ISSUE TITLE
Scanner mit errors nicht in Score 

### ISSUE THREAD

**Issue by MacMic** [SIWECOS/siwecos-core-api#190]
Wenn ein Scanner abbricht oder einen Fehler hat, wird er trotzdem zur Bewertung in den Score gerechnet --> zieht den Score der Webseite nach unten
Siehe auch #156

**Comment by Lednerb** [comment]
Siehe Kommentar in #200:

------------------------

Nach Absprache mit @Skeeve:

* Änderung wird rückgängig gemacht.
* Wenn ein Scanner einen Fehler hat, dann ist der Wert niedriger
  
  * Frage: Hat Scanner einen Timeout (Timeout von uns definiert) oder ist ein Scanner abgestürzt (Speicherproblem etc.)
  * Bei einem Timeout  kann das Ergebnis noch nachgereicht werden, Score wird aktualisiert
  * Scanner tot: Timeout bleibt bestehen
* Recurrent-Scan mit Timeout wird später keine Benachrichtigung an User triggern
* Besser Nutzer sieht erstmal schlechteres Ergebnis mit Timeout (bei manuellem Scan) und kann dann Fehler beheben als dass ein Score von 100 angezeigt wird und der Nutzer später dann einen schlechteren Score erhält, da fehlerhafte / ungenügende Konfigurationen vorliegen
