### ISSUE TITLE
Implement TLS-Scanner Job

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/siwecos-core-api#20]
Aktuell warte ich auf Rückmeldung bezüglich der Übergabe-Parameter des Scanners.

**Comment by ic0ns** [comment]
Hattest du mir ne mail geschickt?

**Comment by Lednerb** [comment]
Nein, im slack Channel habe ich die Frage gestellt:

Lednerb [18:06 Uhr] 
@ic0ns Es wäre praktisch, wenn der TLS-Scanner eine `url` und einen `port` per Query Parameter annehmen würde. Dabei bietet sich wahrscheinlich ein `POST` Request an, da der Scanner ja auch den `dangerLevel` Parameter übergeben bekommen soll.

Ist es möglich, eine URL Anzugeben oder muss zwangsläufig eine IP-Adresse verwendet werden, um den Scan zu starten? (bearbeitet)


Lednerb [18:14 Uhr] 
@ all sollen die einzelnen Scanner nun unter dem `SIWECOS` Namespace bei GitHub geführt und weiterentwickelt werden.

Beim aktuellen Stand blicke ich nicht mehr durch. Welche Versionen werden momentan in der alten siwecos Version verwendet, @ic0ns?
