### ISSUE TITLE
/token/add - Jeder kann die DB mit neuen tokens fluten?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#45]
/token/add hat keinerlei Sicherheitsvorkehrung. Wenn also jemand eine kleine Endlosschleife gegen /token/add feuern läßt…

**Comment by Weegy** [comment]
Wir werden hier eine Whitlist Middleware implementieren, die man über das .env File steuern kann

**Comment by Weegy** [comment]
Es wird ein artisan command für einen mastertoken geben

**Comment by Weegy** [comment]
dieser wird benötigt um weitere Tokens anzulegen
