### ISSUE TITLE
Error in Documentation/api/swagger/scannerapi.yaml

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#50]
In

    TranslateableMessage:
      required:
        - placeholder
      properties:
        placeholder:
          type: string
          description: human readable language placeholder name i.e. HACKED_FILE_FOUND
        values:
          type: string
          description: Key-value pairs that will be used within the language string

values should be an object of key-value pairs.

**Comment by SniperSister** [comment]
Good catch, fixed!
