### ISSUE TITLE
Scanners are not configurable

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#52]
In CoreApi/app/Http/Controllers/ScanController.php

you have

            // dispatch each scanner to the queue
            ScanHeadersJob::dispatch($scan);
            ScanDOMXSSJob::dispatch($scan);
            ScanInfoLeakJob::dispatch($scan);
            // TODO: dispatch TLS-Scanner
            // TODO: Send Response

The consequence is that we have to compile the CoreAPI each time a new scanner is introduced or another scanner has to be decommissioned.

This does not meet the requirements as far as I know.

The scanners must be configurable. Best would be to have it in the database and have API Calls to add, remove, enable and disable them.

**Comment by SniperSister** [comment]
Setting up a database and even API calls seems to be a massive case of overengineering to me. Let's just use a config file for this stuff and we are good to go.

By the way: PHP is compiled on runtime, so there is no need for a compilation process on our side.

**Comment by Skeeve** [comment]
Sorry! ;) My mistake: I was still mentally at Java (Robert's scanner) where compiling is a requirement.

Config files - okay - but it should be possible to adjust them without restart.

Let it be a signal to be sent or re-reading each iteration.

**Comment by SniperSister** [comment]
> Config files - okay - but it should be possible to adjust them without restart.

PHP doesn't work with continuous processes, instead each and every requests creates a full application lifecycle (read files, compile, execute, shut down) so updating a file has an impact on the next request automatically. :)
