### ISSUE TITLE
Create Token fails to set correct aclLevel

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#57]
# Request

```
POST /api/v1/token/add HTTP/1.1
Host: siwecos-core-api.dev
Accept: application/json
Content-Type: application/json
masterToken: wD7YVVc6v4IS8eeghVaTRC/x
Cache-Control: no-cache
Postman-Token: f1fae26e-a1b6-5f8a-6f9a-f231f9b58535

{
"aclLevel":1,
"credits":65536
}
```

! Response

```
{
    "token": "THe9eO22P0Fjx0WxZKffbRb2",
    "hasFailed": false,
    "message": "token successful created"
}
```

Store this token in Postman as mysite.dev's token.

# Database

## Query

```SQL
select * from tokens where token = 'THe9eO22P0Fjx0WxZKffbRb2'
```

## Result

|id |created_at |updated_at |token |credits |active |acl_level |
|---|---|---|---|---|---|---|
|7 |2018-02-08 09:43:36 |2018-02-08 09:43:36 |THe9eO22P0Fjx0WxZKffbRb2 |65536 |true |0 |

### Question

aclLevel is 0 but 1 was requested.

**Comment by Weegy** [comment]
$newToken = new Token(['credits' => $request->json('credits')]);
        if (array_key_exists('aclLevel', $request->json())){
            $newToken->setAclLevel($request->json('aclLevel'));
        }
