### ISSUE TITLE
Storage-Muster Anpassen

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/siwecos-core-api#65]
Core-API soll nur den letzten Scan speichern, BL-API speichert die komplette Historie.

**Comment by Lednerb** [comment]
Siehe auch https://github.com/SIWECOS/siwecos-business-layer/issues/83

**Comment by Lednerb** [comment]
Umgestellt auf `v2`, Core-API liefert Ergebnis nach Scan-Abschluss per Callback an die BLA, diese speichert die Ergebnisse.

Es ist keine gesonderte Interaktion mit der Core-API notwendig.
