### ISSUE TITLE
Scanner controller does not run into a timeout

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#68]
Please see scan_id 75. HEADER scanner didn't finish (for unknown reason) and so the scan cannot complete. The scan was started an 7:16, now it's 8:46.

**Comment by Skeeve** [comment]
As a matter of fact, on monday the header scanner had an issue with botfrei.de and thus did not finish its work.

Due to that the whole scan did not succeed.

Every Scanner must be timed-out in case it crashes.

Additionally every scanner should have the option to tell (via callback url) that it is still working (thus avoiding a timeout) and to tell that it failed (thus avoiding the need of a timeout in case of a caught exception).

**Comment by Skeeve** [comment]
This gets more important as WS_TLS fails to scan https://www.siwecos.de

**Comment by Weegy** [comment]
Has now a 5min Timeout

**Comment by Skeeve** [comment]
Tested. Works with 2 quirks (we talked about it):
1. In registered scan, when viewing existing results, the old results do not get removed when the timeout hits.
2. You do not see, for the timed-out scanners, that they timed out or why there are no results for them. Instead of having a NULL result, maybe an error result would be better, so that it can be shown.

**Comment by Skeeve** [comment]
Scan result is not proper JSON.

Result is (exactly copied from DB)

```
"[{\\n    \\"name\\": \\"TIMEOUT\\",\\n    \\"hasError\\": true,\\n    \\"dangerlevel\\": 0,\\n    \\"errorMessage\\": {\\n        \\"placeholder\\": \\"NO_ERRORS\\",\\n        \\"values\\": []\\n    },\\n    \\"score\\": 0,\\n    \\"scoreType\\": \\"success\\",\\n    \\"testDetails\\": []\\n}]"
```

intended was, I assume

```
[{
  "name": "TIMEOUT",
  "hasError": true,
  "dangerlevel": 0,
  "errorMessage": {
    "placeholder": "NO_ERRORS",
    "values": []
  },
  "score": 0,
  "scoreType": "success",
  "testDetails": []
}]
```

But wouldn't be better:

```
[{
  "name": "TIMEOUT",
  "hasError": true,
  "dangerlevel": 0,
  "errorMessage": {
    "placeholder": "SCANNER_TIMEOUT",
    "values": [
      "scanner": …scannername here…,
      "timeoutvalue": "300",
    ]
  },
  "score": 0,
  "scoreType": "success",
  "testDetails": []
}]
```
So that we could use:

| Placeholder | Text |
|---|---|
|TIMEOUT |Der Scan hat kein Ergebnis geliefert und wurde deswegen abgebrochen. Ist ihre Server abgeschaltet? |
|SCANNER_TIMEOUT |Der %scanner% Scanner hat kein Ergebnis geliefert und wurde nach %timeoutvalue%Sekunden abgebrochen |

Additionally I think the 3 Scanners which failed should send error messages themself.

**Comment by Skeeve** [comment]
I manually changed the results to the format I showed above. Example:

```
[{"name":"TIMEOUT","hasError":true,"dangerlevel":0,"errorMessage":{"placeholder":"SCANNER_TIMEOUT","values":{"scanner":"HEADER","timeoutvalue":"300"}},"score":0,"scoreType":"success","testDetails":[]}]
```

i.e.

```
[{
  "name": "TIMEOUT",
  "hasError": true,
  "dangerlevel": 0,
  "errorMessage": {
    "placeholder": "SCANNER_TIMEOUT",
    "values": {
      "scanner": "HEADER",
      "timeoutvalue": "300"
    }
  },
  "score": 0,
  "scoreType": "success",
  "testDetails": []
}]
```

Problems here are:

1) While "TIMEOUT" is correct, it is not the domain which timed out, it's the scanner,
2) SCANNER_TIMEOUT is not used.

If you take a look at the current status of skeeve.selfhost.eu, scanner "HEADER" you'll see

```
Header Scanner
Letzter Scan: 04.04.2018 06:49

X Zeitüberschreitung

  Der Scan hat kein Ergebnis geliefert und wurde deswegen abgebrochen.

    Ihr Server scheint nicht erreichbar zu sein.
    Ist ihre Server abgeschaltet?
```

Please call me and lets discuss a better way to display the error.

Currently I'm using

* TIMEOUT
* TIMEOUT_ERROR
* TIMEOUT_ERROR_DESC

The real errorMessage Placeholder is not used.

**Comment by Skeeve** [comment]
Update: An example how a core error and a proper scanner error could be returned

# Placeholders

 Placeholder     | Purpose     | Text
-----------------|:-----------:|------
 TIMEOUT         | Category    | Fehler
 TIMEOUT         | Headline    | Zeitüberschreitung
 TIMEOUT         | Negative    | -
 TIMEOUT         | Description | -
 SCANNER_TIMEOUT | Category    | Fehler
 SCANNER_TIMEOUT | Headline    | Der %scanner% Scan hat innerhalb von  %timeoutvalue% Sekunden kein Ergebnis geliefert und wurde  abgebrochen.
 ERROR           | Category    | Fehler
 ERROR           | Headline    | Fehler
 ERROR           | Negative    | -
 ERROR.          | Description | -
 NO_RESPONSE     | Category    | Fehler
 NO_RESPONSE     | Headline    | %domain% antwortet nicht.

## Core Timeout ERROR

```JSON
[{
  "name": "TIMEOUT",
  "hasError": true,
  "dangerlevel": 0,
  "errorMessage": {
    "placeholder": "SCANNER_TIMEOUT",
    "values": {
      "scanner": "INFOLEAK",
      "timeoutvalue": "300"
    }
  },
  "score": 0,
  "scoreType": "success",
  "testDetails": []
}]
```

### Displayed as

> `X` Zeitüberschreitung<br/>
>     Der HEADER Scan hat innerhal von 300 Sekunden kein Ergebnis geliefert und wurde abgebrochen

## Scanner Error

```JSON
[{
  "name": "ERROR",
  "hasError": true,
  "dangerlevel": 0,
  "errorMessage": {
    "placeholder": "NO_RESPONSE",
    "values": {
      "domain": "http://your.do.main",
    }
  },
  "score": 0,
  "scoreType": "success",
  "testDetails": []
}]
```

### Displayed as

> `X` Fehler<br/>
>     http://your.do.main antwortet nicht
