### ISSUE TITLE
Users can effectivly block domain registration

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#69]
One of my accounts (the bad guy) registered https://non.existing.de which does not belong to him and (of course) did not validate.
Another user tried (the good guy) to register https://non.existing.de but is forbidden to, as the bad guy already holds it.

Proposal: As long as a domain is not validated, anyone can register.

The first one to validate will make all the other registered domains by the same name invalid.

**Comment by Weegy** [comment]
Fixed

**Comment by Skeeve** [comment]
Szenario:

1. User1 registers domainA - does not validate yet
2. User2 registers domainB - does not even inted to validate it
3. User1 lost domainA

While user 1 can re-register domainA it might be reason for him to call support.

My idea was that User1 AND User2 both have a separate entry for domainA as being unvalidated. The first one to validate with his own specific domain token, will receive domainA and only then will the other user lose it.

**Comment by Weegy** [comment]
With the current scheme where the Domain is a unique entry, this will be very hard to achieve
