### ISSUE TITLE
Regular scans of domains don't work

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#71]
Seems domains are not scanned regularly. Currently we seem to have to manually invoke rescans.

**Comment by Weegy** [comment]
Added nightly recurrent scan at 01:00

**Comment by SniperSister** [comment]
All scans being dispatched at once? Wouldn’t that kill the scanning servers?

**Comment by Skeeve** [comment]
I couldn't see any scan being dispatched this night.

Check

```SQL
select url,created_at
from scans
where created_at < '2018-03-14 05:00'
order by created_at desc
```

And the maximum date will be 2018-03-13 20:47:38

**Comment by Skeeve** [comment]
Question arose: What if a domain, which should have been scanned, was unavailable when the regular scan was about to start? Will it be retried automatically some time later?

**Comment by Weegy** [comment]
```
foreach ( $_ENV as $key => $value ) {
			if ( ! preg_match( "/^SCANNER_(\w+)_URL$/", $key, $scanner_name ) ) {
				continue;
			}
			if ( ! preg_match( "/^https?:\/\//", $value ) ) {
				continue;
			}
			ScanJob::dispatch( $scanner_name[1], $value, $scan );
		}
```
I think this will be the problem while in cronmode. Can you please check this @Skeeve ?

**Comment by Weegy** [comment]
Environment file will not be read by cron command
will implement a failover

**Comment by Weegy** [comment]
Fixed, Scan will be 24h after last one

**Comment by Skeeve** [comment]
Waht's the failover you implemented?

**Comment by Skeeve** [comment]
Found this

```
	    $scannerUrls = array();
	    $scannerUrls['SCANNER_HEADER_URL'] = 'http://scanner.staging2.siwecos.de/live-hshs/current/public/api/v1/header';
	    $scannerUrls['SCANNER_DOMXSS_URL'] = 'http://scanner.staging2.siwecos.de/live-hshs/current/public/api/v1/domxss';
	    $scannerUrls['SCANNER_INFOLEAK_URL'] = 'http://scanner.staging2.siwecos.de/live-leak/current/';
	    $scannerUrls['SCANNER_INI_S_URL'] = 'http://scanner.staging2.siwecos.de/ini-s-mwege/current/';
	    $scannerUrls['SCANNER_WS_TLS_URL'] = 'http://scanner.staging2.siwecos.de:8080/start';
```

This is just a workaround :( We should strictly separate configuration data from code.

**Comment by Weegy** [comment]
Changed cron to source the .env file (thanks to @Skeeve)
Hopefully it will work as expected

**Comment by Skeeve** [comment]
Didn't work but works now see #77
