### ISSUE TITLE
No Error Messages

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#74]
While HEADE, DOMXSS and INFOLEAK scanners do provide an error, it is discarded / ignored by the core.

See papertrail and search for `/ 4721`. You'll find lots of errorMessages, none of them appears in the scan_results in the DB.

**Comment by Weegy** [comment]
Errorhandling should now be fixed

**Comment by Skeeve** [comment]
Not yet fixxed as explained in Slack.
