### ISSUE TITLE
Message: "Starten des Scans fehlgeschlagen, bitte versuchen Sie es später erneut"

### ISSUE THREAD

**Issue by mniemietz** [SIWECOS/siwecos-core-api#81]
I am not sure if this is the right place to insert this issue but can you verify (and fix) why it is not possible to scan "zdf.de"? Thank you.

**Comment by Weegy** [comment]
Jepp, will check ASAP

**Comment by y-ates** [comment]
Redeploy the InfoLeak-Scanner before further investigating.

**Comment by Weegy** [comment]
Look like it ran into a timeout from a scanner. Papertrail starts two scanners in normal time, the third one is far slower.

**Comment by Weegy** [comment]
It seems like the InfoLeak Scanner runs into a fatal error @mniemietz.

**Comment by ic0ns** [comment]
what does it respond with?

**Comment by Weegy** [comment]
Redeploy of Infoleak fixes the error
